### ISSUE TITLE
The Insights, Apps, Gear part is not responsive

### ISSUE THREAD

**Issue by RaminMammadzada** [tadeuasarro/BuildingWithResponsiveDesign#2]
As you see in the screenshot below, the Insights, Apps Gear part is not responsive:
![image](https://user-images.githubusercontent.com/4702114/86369486-312f1f00-bc87-11ea-9239-e42da15444c8.png)

**Comment by Prabhakarzx** [comment]
### Dear @RaminMammadzada,
Thanks for your suggestions. It is fixed now!
Thanks!
